# Nome da aplicação
spring.application.name=api_restaurante

# Contexto da aplicação
server.servlet.context-path=/api_restaurante

# URL do banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/jg_restaurante_caseiro?useSSL=false&serverTimezone=UTC

# Usuario do banco de dados
spring.datasource.username=joaozim

# Senha do banco de dados
spring.datasource.password=Joaozim22334455

# Driver de conexão do banco de dados
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Evita a recriação das tabelas
spring.jpa.hibernate.ddl-auto=none